<?php
date_default_timezone_set('Asia/Tehran');
    require_once("database.php");
    require_once("users.php");
    require_once("sessions.php");
    require_once("rooms.php");
    require_once("foods.php");
    require_once("functions.php");
?>
